apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: garytrek/web:1.0
        name: web
        volumeMounts:
        - mountPath: /app
          name: app
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
        livenessProbe:
          tcpSocket:
            port: 8000    
      initContainers:
      - image: busybox:1.31.0
        name: web-init
        command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
        volumeMounts:
        - mountPath: /app
          name: app
      volumes:
      - name: app
        emptyDir: {}
    
