apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    env: dev
spec:
  containers:
  - image: garytrek/web:1.0
    name: nginx
    volumeMounts:
    - mountPath: /app
      name: app

  - image: busybox:1.31.0
    name: web-init
    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
    volumeMounts:
    - mountPath: /app
      name: app

  volumes:
  - name: app
    emptyDir: {}


